# CI de Nível 03 - Disparo a após a conclusão de um pipeline

# Nome do nosso 'pipeline'
name: 'Execução por Deploy'

# Regras de Disparo (Gatilhos/Triggers)
# Gatilho de exec manual = workflow_dispatch
# Gatilho de exec agendada = schedule
# Gatilho de exec a partir de outro pipe = workflowrun

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# Trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    #Maquina que o job vai executar
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalação do yarn
      - name: Instalando o yarn
        run: npm install -g yarn

      #instalação das dependencias
      - name: Instalando dependencias
        run: yarn

      #Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      #Executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e

      # Gera um artefato com o report do playwright em arquivo
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report

      # Gera o relatório após os testes
      - name: Publicar resultado no PR
        uses: dorny/test-reporter@v1
        if: ${{ !cancelled() }}
        with:
          name: Test Report
          path: ./test-results/results.xml
          reporter: java-junit
