# CI de Nivel 04 - Disparo dos testes dentro do pipe de dev

name: 'Execução Integrada'

on:
  workflow_dispatch:
    
jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executanto testes de unidade
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalação do yarn
      - name: Instalando o yarn
        run: npm install -g yarn

      #instalação das dependencias
      - name: Instalando dependencias
        run: yarn

      #Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      #Executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e

      # Gera um artefato com o report do playwright em arquivo
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"